In [42]:
import numpy as np
import pandas as pd
import scipy.spatial
from collections import Counter
from scipy.spatial import distance

In [43]:
df= pd.read_excel('assignment6.xlsx')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [44]:
df['versicolor']=pd.get_dummies(df['species'], drop_first=True)
df.head(10)

,sepal_length,sepal_width,petal_length,petal_width,species,versicolor
0,5.1,3.5,1.4,0.2,setosa,0
1,4.9,3.0,1.4,0.2,setosa,0
2,4.7,3.2,1.3,0.2,setosa,0
3,4.6,3.1,1.5,0.2,setosa,0
4,5.0,3.6,1.4,0.2,setosa,0
5,7.0,3.2,4.7,1.4,versicolor,1
6,6.4,3.2,4.5,1.5,versicolor,1
7,6.9,3.1,4.9,1.5,versicolor,1
8,5.5,2.3,4.0,1.3,versicolor,1
9,6.5,2.8,4.6,1.5,versicolor,1

In [45]:
df_test = pd.DataFrame(df,columns=df.columns[:-2])          #train X dataset
X_train= df_test  
X_train.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [46]:
y_train= df['versicolor']                         #train y dataset

In [47]:
data = {'sepal_length': [8.2], 'sepal_width': [2.6], 'petal_length':[3.2], 'petal_width':[1.8]}  
X_test = pd.DataFrame(data)                         #test X dataset
#X_test.head()

In [48]:
class KNN:
    def __init__(self, k):
        self.k = k
        
    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        
    
    def predict(self, X_test):
        final_output = []
        for i in range(len(X_test)):
            d = []
            votes = []
            for j in range(len(X_train)):
                dist = scipy.spatial.distance.euclidean(X_train.iloc[[j]] , X_test.iloc[[i]])
                d.append([dist, j])
            d.sort()
            d = d[0:self.k]
            for d, j in d:
                votes.append(y_train[j])
            ans = Counter(votes).most_common(1)[0][0]
            final_output.append(ans)
            
        return final_output

In [49]:
clf = KNN(7)
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)
for i in prediction:
    print(i, end= ' ')

1